blog_posts/urls.py
from django.urls import path
from blog_posts import views

urlpatterns = [

    path('', views.PostIndex.as_view(), name='blog_index'),
    path('categoria/<str:categoria>', views.PostCategoria.as_view(), name='post_categoria'),
    path('busca/', views.PostBusca.as_view(), name='post_busca'),
    path('novo/', views.PostCreate.as_view(), name='novo-post'),
    path('update/<int:pk>', views.PostUpdateView.as_view(), name='update-post'),
    path('delete/<int:pk>', views.PostDeleteView.as_view(), name='delete-post'),
    path('post/<int:pk>', views.PostDetalhes.as_view(), name='post_detalhes'),

    path('sobre_nos/', views.sobre_nos.as_view(), name='sobre_nos'),
    

]

raiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    #path('', include('principal.urls')),
    path('', include('blog_posts.urls')),
    path('categorias/', include('blog_categorias.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = "blog_posts.views.handler403" #url para a pagina de erro 403
handler404 = "blog_posts.views.handler404" #url para a pagina de erro 404
handler500 = "blog_posts.views.handler500" #url para a pagina de erro 500

blog_comentarios/models.py
from django.db import models

# Create your models here.

from blog_posts.models import Post
from django.contrib.auth.models import User
from django.utils import timezone

class Comentario(models.Model):

    nome_comentario = models.CharField(max_length=150, verbose_name='Nome')
    email_comentario = models.EmailField(verbose_name='E-mail')
    comentario = models.TextField(verbose_name='Comentário')
    post_comentario = models.ForeignKey(Post, on_delete=models.CASCADE)
    usuario_comentario = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True)
    data_comentario = models.DateTimeField(default=timezone.now)
    publicad_comentario = models.BooleanField(default=False) # lembrar na hora de refatorar de colocar o nome Publicado_comentario

    def __str__(self):
        return self.nome_comentario    

blog_posts/models.py
from django.db import models

# Create your models here.

from blog_categorias.models import Categoria
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image
from django.conf import settings
import os



class Post(models.Model):

    titulo_post = models.CharField(max_length=255, verbose_name='Titulo')
    autor_post = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='Autor')
    data_post = models.DateTimeField(default=timezone.now, verbose_name='Data da Publicação')
    conteudo_post = models.TextField(verbose_name='Conteúdo')
    excerto_post = models.TextField(verbose_name='Sumário')
    categoria_post = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING, blank=False, null=False, verbose_name='Categoria')
    imagem_post = models.ImageField(upload_to='post_img/%Y/%m/%d', blank=False, null=False, verbose_name='Imagem')
    publicado_post = models.BooleanField(default=False, verbose_name='Publicado')

    def __str__(self):
        return self.titulo_post   


    # metodo responsavel por redimencionar a imagem
  #  def save(self, *args, **kwargs):
  #      super().save(*args, **kwargs) 

    #    self.resize_image(self.imagem_post.name, 800)

    # continuação do metodo responsavel por redimencionar a imagem
   # @staticmethod
   # def resize_image(img_name, new_width):

     #   img_path =  os.path.join(settings.MEDIA_ROOT, img_name)  

      #  img = Image.open(img_path)

       # width, height = img.size

        #new_height = round((new_width * height) / width)


        #if width <= new_width:
         #   img.close()
          #  return

        #new_image = img.resize((new_width, new_height), Image.ANTIALIAS)

        #new_image.save(

         #   img_path,
          #  optimize=True,
          #  quality=60

        #)
        #new_image.close()

blog_posts/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post

        fields = ['titulo_post', 'excerto_post', 'conteudo_post', 'autor_post', 'categoria_post', 'imagem_post', 'publicado_post']

        widgets = {
            
            'titulo_post': forms.TextInput(attrs={'placeholder':'Titulo', 'class': 'form-control form-control-lg'}),
            'excerto_post': forms.TextInput(attrs={'placeholder':'Súmario', 'class': 'form-control form-control-lg'}),
            'conteudo_post':SummernoteWidget(),
            'autor_post': forms.Select(attrs={'placeholder':'Post', 'class': 'form-control form-control-lg'}),
            'categoria_post': forms.Select(attrs={'placeholder':'Post', 'class': 'form-control form-control-lg'}),
            'imagem_post': forms.FileInput(attrs={'id':'validatedCustomFile'}),
            '': forms.CheckboxInput(attrs={'class': 'required checkbox form-control'}),
            
        }

blog_posts/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView

from .models import Post
from .forms import PostForm
from django.db.models import Q, Count, Case, When
from blog_comentarios.forms import FormComentario
from blog_comentarios.models import Comentario
from django.contrib import messages



def handler403(request, exception): # função para direcionar a pagina de erro 403
    return    render(request, 'erro403.html')

def handler404(request, exception): # função para direcionar a pagina de erro 404
    return    render(request, 'erro404.html')

def handler500(request): # função para direcionar a pagina de erro 505
    return    render(request, 'erro500.html')


        
class sobre_nos(ListView):
    
    model = Post
    form_class = PostForm
    template_name = 'blog_posts/sobre_nos.html'
   

#def sobre_nos(request): # função para direcionar a pagina de erro 505
 #   return    render(request, 'sobre_nos.html')    


class PostIndex(ListView):
    
   model = Post #model usado para preencher 
   template_name = 'blog_posts/blog_index.html'#direcionando para o template
   paginate_by = 6 # quantos posts vao ficar na pagina
   context_object_name = 'posts'#objeto de busca
   
   #funcao para colocar os posts em ordem do ultimo adicionado(mais recente)
   def get_queryset(self):
       qs = super().get_queryset()# refazendo o query set com a variavel qs
       qs = qs.select_related('categoria_post')
       qs = qs.order_by('-id').filter(publicado_post=True)#ordenando os posts na variavel qs e faz a busca apenas nos postes publicados
       

       qs = qs.annotate(# parte da funçao que separa os comentarios publicados

          

           numero_comentarios=Count( #Count = contar
               Case( #Case = caso
                   When(comentario__publicad_comentario=True, then=1) #when = quando obs : lembrar na hora de refatorar de colocar o nome Publicado_comentario

               )

           )
            
       )

       return qs
class PostBusca(PostIndex):

    template_name = 'blog_posts/posts_busca.html'#direcionando para o template

    def get_queryset(self):
        qs = super().get_queryset() #começa a fazer a busca

        termo = self.request.GET.get('termo') # usa o argumento termo referenciado no html no label da busca

        if not termo: # se a busca retornar vazia
            return qs # retorna qs vazio

        qs = qs.filter( # fazendo filtro no campo de busca

            # os campos abaixo fazem a busca pelos campo especificados no models

           Q(titulo_post__icontains=termo) |
           Q(autor_post__first_name__iexact=termo) |
           Q(conteudo_post__icontains=termo) |
           Q(excerto_post__icontains=termo) |
           Q(categoria_post__nome_categoria__iexact=termo) 

           # icontains faz a busca sem case sensitive e iexact tambem faz a busca sem case sensitive mas para chave estrangeira

        )

        return qs


class PostCategoria(PostIndex):

    template_name = 'blog_posts/posts_categoria.html'#direcionando para o template

    def get_queryset(self): #começa a fazer a busca por categorias
        qs = super().get_queryset()

        categoria = self.kwargs.get('categoria', None)

        if not categoria:
            return qs

        qs = qs.filter(categoria_post__nome_categoria__iexact=categoria)    
        # o filtro acima busca a chave estrangeira categoria e em seguida com o __ busca o campo e en seguida __ o iexact faz a busca sem case sensitive


        return qs


class PostDetalhes(UpdateView):
    
    template_name = 'blog_posts/post_detalhes.html'#direcionando para o template
    model = Post #model usado para preencher 

    form_class = FormComentario

    context_object_name = 'post'

    def get_context_data(self, **kwargs):

        contexto = super().get_context_data(**kwargs)

        post = self.get_object()

        comentarios = Comentario.objects.filter(publicad_comentario=True,
                                                post_comentario=post.id )

        contexto ['comentarios'] = comentarios                                       


        return contexto
    
    def form_valid(self, form):

        post = self.get_object()

        comentario = Comentario(**form.cleaned_data)

        comentario.post_comentario = post

        if self.request.user.is_authenticated:
            comentario.usuario_comentario = self.request.user

        comentario.save()   

        messages.success(self.request, 'Comentário enviado com sucesso!!!') 

        return redirect('post_detalhes', pk=post.id)

       
        
class PostCreate(CreateView):
    
    model = Post
    form_class = PostForm
    template_name = 'blog_posts/novo_post.html'
    success_url ="/"


class PostUpdateView(UpdateView):
    
    model = Post
    form_class = PostForm
    template_name = 'blog_posts/editar_post.html'
    success_url ="/"

class PostDeleteView(DeleteView):  
    model = Post  
    template_name = 'blog_posts/deletar_post.html'
    success_url ="/"        

blog_posts/templates/blog_posts/blog_index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}


<!-- Conteudo -->

{% block content %}

<main>
    <!--? slider Area Start-->
    <!--================lugar do carrolssel =================-->
    <!-- slider Area End-->  
     
 
</main>

 <!--================Blog Area =================-->
   <section class="blog_area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mb-5 mb-lg-0">
                
                {% if user.is_authenticated %}
      
                <div class="header-right-btn d-none d-lg-block ml-20">
                    <a href="{% url 'novo-post' %}" class="sc-add-to-cart btn btn-primary">Novo Post</a>
                 </div>
                 <p></p>
            
                {% endif %}
                                 
                <div class="blog_left_sidebar">
                                            
                    {% for post in posts %}

                    <article class="blog_item">

                        <a class="d-inline-block" href="{% url 'post_detalhes' post.id %}">
                            <h2>{{ post.titulo_post }}</h2>
                        </a>
                        
                        <div class="blog_item_img">

                            <a href="{% url 'post_detalhes' post.id %}"><img class="card-img rounded-0" src="{{ post.imagem_post.url }}" alt=""></a>
                            
                            <a href="{% url 'post_detalhes' post.id %}" class="blog_item_date">
                            
                                    {{ post.data_post|naturalday|title }}<!--usa o metodo humanize referenciado no instal apps para formatar a data-->
                            </a>
                        </div>

                        <div class="blog_details">
                            <a class="d-inline-block" href="{% url 'post_detalhes' post.id %}">
                                <h2>{{ post.excerto_post }}</h2>
                            </a>
                            
                            <ul class="blog-info-link">
                                <li><i class="fa fa-user"></i> Autor: {{ post.autor_post }}</a></li>
                                <li><i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>Categoria: {{ post.categoria_post }}</a></li>
                                
                                <li><i class="fa fa-comments"></i> {{ post.numero_comentarios }} Comentário(s)</a></li>
                            </ul>
                        </div>
                    </article>
                    {% endfor %}

              <!--================inserindo paginação =================-->
                    {% include 'parciais/_pagination.html' %}
                    
                </div>

            </div>
            <!--================inserindo barra lateral =================-->
                    {% include 'parciais/_lateral.html' %} 
        </div>
    </div>
</section>
<!--================Blog Area =================-->




{% endblock %}



<!--/Conteudo-->


 

            

blog_posts/templates/blog_posts/deletar_post.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="jumbotron">
        <h4 class="display-5">Você tem certeza que deseja deletar {{ deletar.titulo_post }}?</h4>
        <form method="POST">
            {% csrf_token %}
            <a href="{% url 'blog_index' %}" class="sc-add-to-cart btn btn-primary">Não</a>
            <button type="submit" class="sc-add-to-cart btn btn-danger">Deletar</button>
        </form>        
    </div>

{% endblock %}



<form method="post">{% csrf_token %}
     
 
    <p>Are you sure you want to delete "{{ object }}"?</p>
     
     
        <input type="submit" value="Confirm">
</form>

blog_posts/templates/blog_posts/editar_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
        <div class="col-md-4 offset-md-2">
        <h1>Editar Post</h1>
        </div>
{% endblock %}



{% block content %}

        <div class="col-md-4 offset-md-2">

            <form method="POST" enctype="multipart/form-data" id="form">

                    <div class="form-group">

                            <div class="row">
                                    
                            {% csrf_token %}
                           
                            {{ form|crispy }}
                            
                            {{ conteudo_post|safe }}
                            
                            </div>

                    </div>

                <button type="submit" class="btn btn-success">Salvar</button>
            </form>

        </div>

{% endblock %}

blog_posts/templates/blog_posts/novo_post.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}
{% load static %}





{% block title %}
        <div class="col-md-4 offset-md-2">
            <h1>Novo Post</h1>
        </div>
{% endblock %}



{% block content %}

        <div class="col-md-4 offset-md-2">

            <form method="POST" enctype="multipart/form-data" id="form">

                    <div class="form-group">

                            <div class="row">
                                    
                            {% csrf_token %}
                           
                            {{ form|crispy }}
                            
                            
                            </div>

                    </div>

                <button type="submit" class="btn btn-success">Salvar</button>
            </form>

        </div>

{% endblock %}

blog_posts/templates/blog_posts/post_detalhes.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block content %}




                <!-- POST -->
                <main>

                   

                        <div class="container">
                            
                            <div class="row pt-5"> 
                                
                                <div class="col-xl"></div>

                                <div class="col-xl-8 text-center">

                                    {% if user.is_authenticated %}
                                  
                                    <div>
                                        
                                        <a href="{% url 'novo-post' %}" class="sc-add-to-cart btn btn-primary">Novo Post</a>
                                        <a href="{% url 'update-post' post.id %}" class="sc-add-to-cart btn btn-primary">Editar</a>
                                        <a href="{% url 'delete-post' post.id %}" class="sc-add-to-cart btn btn-danger">Deletar</a>

                                    </div>
                                    <p></p>

                                    {% endif %}
                                    
                                    <h1>{{ post.titulo_post }}</h1>
                                    <h5>{{ post.excerto_post }}</h5>
                                    <p class="text-muted mt-4">
                                        <small>
                                            {{ post.autor_post }} | {{ post.data_post }} | {{ post.categoria_post }}
                                        </small>
                                        
                                    </p>
                                </div>
                                <div class="col-xl">
                                   
                                </div>
                                
                            </div>

                            <div class="row pt-5">
                                
                                <div class="col-xl">
                                                                
                                    
                                </div>

                                <div class="col-xl-8">

                                    {% if post.imagem_post %}

                                  
                                    <!--<img class="img-fluid pb-5 " src="{{ post.imagem_post.url }}" alt="{{ post.titulo_post }}">--> 

                                    {% endif %}

                                    {{ post.conteudo_post|safe }}


                                </div>
                                <div class="col-xl"></div>
                            </div>

                            {% if comentarios %}
                            <div class="row pt-5">
                                <div class="col-xl"></div>
                                <div class="col-xl-8">
                                    <h2 class="my-3">Comentários ({{ comentarios.count }})</h2>

                                    {% for comentario in comentarios  %}

                                    <h5 class="mb-2 mt-5">{{ comentario.nome_comentario }} disse:</h5>
                                    <small class="text-muted">{{ comentario.data_comentario }}</small>
                                    <p class="mb-1">{{ comentario.comentario }}</p>

                                    {% endfor %}       



                                </div>
                                <div class="col-xl"></div>
                            </div>
                            
                            {% endif %}

                            <div class="row pt-5">
                                <div class="col-xl"></div>
                                <div class="col-xl-8">
                                    <h2 class="my-3">Deixe um comentário</h2>

                                    <form method="POST" action="#envia_comentario">

                                            {% csrf_token %}

                                        <table class="table">
                                            
                                            {{ form|crispy }}

                                            <tr>
                                                <td colspan="2">

                                                    <div class="g-recaptcha" data-sitekey="6LdmuVgdAAAAAI_QTfwi8llmTA7C4O0ShEmkhpez"></div>
                                                    <br/>

                                                    {% include 'parciais/_messages.html' %}
                                                    <input id="envia_comentario" type="submit" class="btn btn-primary"
                                                        value="Enviar">
                                                </td>
                                            </tr>
                                        </table>
                                    </form>


                                </div>
                                <div class="col-xl"></div>
                            </div>
                        </div>

                                               

            </main>
                <!-- POST -->

{% endblock %}

blog_posts/templates/blog_posts/posts_busca.html
{% extends 'base.html' %}


{% load humanize %}


{% block titulo %} Busca {% endblock %}

<!-- CONTENT -->
{% block content %}

<!--================Blog Area =================-->
<section class="blog_area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mb-5 mb-lg-0">
                
                                
                <div class="blog_left_sidebar">
                                            
                    {% for post in posts %}

                    <article class="blog_item">
                        <div class="blog_item_img">
                            <img class="card-img rounded-0" src="{{ post.imagem_post.url }}" alt="">
                            <a href="#" class="blog_item_date">
                            
                                    {{ post.data_post|naturalday|title }}<!--usa o metodo humanize referenciado no instal apps para formatar a data-->
                          
                            </a>
                        </div>

                        <div class="blog_details">
                            <a class="d-inline-block" href="{% url 'post_detalhes' post.id %}">
                                <h2>{{ post.titulo_post }}</h2>
                            </a>
                            <p>{{ post.exerto_post }}</p>
                            <ul class="blog-info-link">
                                <li><a href="#"><i class="fa fa-user"></i> Autor: {{ post.autor_post }}</a></li>
                                <li><a href="#"><i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>Categoria: {{ post.categoria_post }}</a></li>
                                
                                <li><a href="#"><i class="fa fa-comments"></i> {{ post.numero_comentarios }} Comentário(s)</a></li>
                            </ul>
                        </div>
                    </article>
                    {% endfor %}

                   <!--================inserindo paginação =================-->
                         {% include 'parciais/_pagination.html' %}
                </div>

            </div>
            
          <!--================inserindo barra lateral =================-->
                    {% include 'parciais/_lateral.html' %} 
        </div>
    </div>
</section>
<!--================Blog Area =================-->


<!--/CONTENT-->
{% endblock %}

blog_posts/templates/blog_posts/posts_categoria.html
{% extends 'base.html' %}


{% load humanize %}


{% block titulo %} Categoria {% endblock %}

<!-- CONTENT -->
{% block content %}

        <div class="card-columns mt-4">

                <!-- FOR LOOP -->
                {% for post in posts %}<!-- a varialvel post faz referencia ao que deve ser usado no html e o posts ta sendo trazido da viewr com a pesquisa-->
                        <div class="card">
                         {% if post.imagem_post %}   
                                <a href="{% url 'post_detalhes' post.id %}">
                                    <img class="card-img-top"
                                            src="{{ post.imagem_post.url }}"
                                            alt="{{ post.titulo_post }}">
                                </a>
                          {% endif %}      

                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{% url 'post_detalhes' post.id %}">
                                    {{ post.titulo_post }}
                                </a>
                            </h5>
                            <p class="card-text">{{ post.exerto_post }}</p>
                            <p class="card-text">

                                <small class="text-muted">

                                    {{ post.data_post|naturalday|title }}<!--usa o metodo humanize referenciado no instal apps para formatar a data-->
                                    |
                                    {{ post.numero_comentarios }} Comentário(s)
                                    <!-- esse jeito abaixo apenas conta quantos comentarios tem o post o no acima separa os comentarios publicados ou não-->
                                    <!--{{ post.comentario_set.count }} Comentário(s)<!-- conta e mostra quantos comentarios existem pra determinado post, obs:comentario é um foreidkey -->
                                    |
                                    {{ post.categoria_post }}<!--lista e associa a categoria cadastrada pra determinadado post, obs: categoria é um foreidkey -->

                                </small>

                            </p>

                            <div class="text-right">
                                <a href="{% url 'post_detalhes' post.id %}" class="btn btn-outline-secondary">Ler mais...</a>
                            </div>
                        </div>
                        </div>
                <!--/FOR LOOP-->
                {% endfor %}
        </div>

<!--/CONTENT-->
{% endblock %}

blog_posts/templates/blog_posts/sobre_nos.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}




{% block content %}

  

      <!-- Principal jumbotron, para a principal mensagem de marketing ou call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Projeto Prometheus</h1>
          <p>Iniciativa sem fins lucrativos que busca propagação de conhecimento .</p>
          <!--<p><a class="btn btn-primary btn-lg" href="#" role="button">Saiba mais &raquo;</a></p> -->
        </div>
      </div>

      <div class="container">
        <!-- Exemplo de linha de colunas -->
        <div class="row">
          <div class="col-md-4">
            <h2>Nossa História</h2>
            <p>A idéia surgiu diante da necessidade de sempre estar revendo os mesmos artigos que por vezes estavam desatualizados ou com descrições incorretas.
              Diante dessa dificuldade o projeto surgiu para ajudar no desenvolvimento e com informações basicas mas, atualizadas para serem usadas no dia-a-dia. </p>
          
          </div>
          <div class="col-md-4">
            <h2>Objetivos</h2>
            <p>Propagar o conhecimento, troca de informações e maneiras diferentes e mais simples de resolver problemas .
              Aprender e ensinar... </p>
           
          </div>
          <div class="col-md-4">
            <h2>Toda ajuda Possivel !!!</h2>
            <p>Alguns artigos foram copiados de outras fontes, porém em todos eles está referênciado o autor original e o endereço para a postagem original..</p>
           
          </div>
        </div>

        <hr>

      </div> <!-- /container -->



      {% endblock %}